version: "1.0"

services:
  website:
    image: ecommerce/image
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ecommerce-website
    volumes:
      - .:/app
      - /app/node_modules
      # - /app/.next
    ports:
      - ${PORT:-3000}:3000
    restart: unless-stopped
    environment:
      NODE_ENV: development